# Generated by Django 4.0.6 on 2023-01-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20, unique=True)),
                ('description', models.TextField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='project/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
